In [2]:
#import libraries
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb
import pandas as pd

In [4]:
#importing data
ds=pd.read_csv("raw_messy_dataset.csv")
ds

Name      Age Gender              Email     Join_Date Salary  \
0      Alice      NaN    NaN  user0@example.com    2021-05-21    NaN   
1        Bob       40      M  user1@example.com           NaN  50000   
2    Charlie  unknown   Male  user2@example.com    2020/01/01  50000   
3      David      NaN    NaN  user3@example.com    2021-05-21  70000   
4        Eva       35  Other  user4@example.com  July 4, 2020  70000   
..       ...      ...    ...                ...           ...    ...   
100    Alice      NaN    NaN  user0@example.com    2021-05-21    NaN   
101      Bob       40      M  user1@example.com           NaN  50000   
102  Charlie  unknown   Male  user2@example.com    2020/01/01  50000   
103    David      NaN    NaN  user3@example.com    2021-05-21  70000   
104      Eva       35  Other  user4@example.com  July 4, 2020  70000   

      Department  
0          Admin  
1    Engineering  
2             HR  
3          Admin  
4    Engineering  
..           ...  
100        Admin  
101  Engineering  
102           HR  
103        Admin  
104  Engineering  

[105 rows x 7 columns]

In [6]:
#checking details
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105 entries, 0 to 104
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Name        105 non-null    object
 1   Age         72 non-null     object
 2   Gender      89 non-null     object
 3   Email       95 non-null     object
 4   Join_Date   70 non-null     object
 5   Salary      78 non-null     object
 6   Department  89 non-null     object
dtypes: object(7)
memory usage: 5.9+ KB


In [7]:
ds.describe()

Name Age Gender              Email   Join_Date Salary   Department
count     105  72     89                 95          70     78           89
unique     10   5      5                 90           4      5            5
top     Alice  40   Male  user0@example.com  2021-05-21  50000  Engineering
freq       11  22     22                  2          26     22           26

In [13]:
#searching for duplicates
ds.duplicated().sum()


0

In [14]:
#remove duplicates
ds.drop_duplicates(inplace=True)
#go to 13 cell

In [22]:
#returns column
ds.columns

Index(['Name', 'Age', 'Gender', 'Email', 'Join_Date', 'Salary', 'Department'], dtype='object')

In [20]:
#heading age or changed type of age to numeric from object
ds["Age"]=pd.to_numeric(ds["Age"],errors = 'coerce')

In [21]:
ds.info

<bound method DataFrame.info of        Name   Age Gender              Email     Join_Date Salary   Department
0     Alice   NaN    NaN  user0@example.com    2021-05-21    NaN        Admin
1       Bob  40.0      M  user1@example.com           NaN  50000  Engineering
2   Charlie   NaN   Male  user2@example.com    2020/01/01  50000           HR
3     David   NaN    NaN  user3@example.com    2021-05-21  70000        Admin
4       Eva  35.0  Other  user4@example.com  July 4, 2020  70000  Engineering
..      ...   ...    ...                ...           ...    ...          ...
95    Frank   NaN   Male                NaN           NaN  50000          NaN
96    Grace  40.0   Male                NaN           NaN  70000        Sales
97   Hannah   NaN   Male                NaN    2020/01/01  60000          NaN
98      Ivy   NaN      F                NaN    2020/01/01  50000          NaN
99     Jack   NaN    NaN                NaN  July 4, 2020  60000        Admin

[100 rows x 7 columns]>

In [24]:
#finding median for missing value in column age
x=ds["Age"].median()
#filling age at empty cell
ds["Age"].fillna(x,inplace=True)

C:\Users\adity\AppData\Local\Temp\ipykernel_17748\1489819508.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  ds["Age"].fillna(x,inplace=True)


In [26]:
#for checking is there empty
ds["Age"].unique()

array([35., 40., 30., 25.])

In [27]:
ds["Gender"].unique()

array([nan, 'M', 'Male', 'Other', 'Female', 'F'], dtype=object)

In [33]:
#standardizing colmn gender for unique values
ds["Gender"]=ds["Gender"].replace({
    "M":"Male","F":"Female","":"None"
})

In [34]:
ds["Gender"].unique()

array([nan, 'Male', 'Other', 'Female'], dtype=object)

In [37]:
#handling email colums
ds["Email"].fillna("-",inplace=True)

In [39]:
print(ds.to_string())

       Name   Age  Gender               Email     Join_Date   Salary   Department
0     Alice  35.0     NaN   user0@example.com    2021-05-21      NaN        Admin
1       Bob  40.0    Male   user1@example.com           NaN    50000  Engineering
2   Charlie  35.0    Male   user2@example.com    2020/01/01    50000           HR
3     David  35.0     NaN   user3@example.com    2021-05-21    70000        Admin
4       Eva  35.0   Other   user4@example.com  July 4, 2020    70000  Engineering
5     Frank  35.0   Other   user5@example.com           NaN    70000        Admin
6     Grace  35.0  Female   user6@example.com  July 4, 2020    80000  Engineering
7    Hannah  35.0   Other   user7@example.com    2021-05-21      NaN           HR
8       Ivy  30.0  Female   user8@example.com           NaN    50000  Engineering
9      Jack  35.0    Male   user9@example.com    2020/01/01    80000  Engineering
10    Alice  35.0    Male  user10@example.com    2021-05-21    70000  Engineering
11      Bob  35.

In [40]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Name        100 non-null    object 
 1   Age         100 non-null    float64
 2   Gender      86 non-null     object 
 3   Email       100 non-null    object 
 4   Join_Date   66 non-null     object 
 5   Salary      74 non-null     object 
 6   Department  84 non-null     object 
dtypes: float64(1), object(6)
memory usage: 6.2+ KB


In [42]:
#handling joint date to date time formate
ds["Join_Date"]=pd.to_datetime(ds["Join_Date"],errors = 'coerce')


In [43]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype         
---  ------      --------------  -----         
 0   Name        100 non-null    object        
 1   Age         100 non-null    float64       
 2   Gender      86 non-null     object        
 3   Email       100 non-null    object        
 4   Join_Date   24 non-null     datetime64[ns]
 5   Salary      74 non-null     object        
 6   Department  84 non-null     object        
dtypes: datetime64[ns](1), float64(1), object(5)
memory usage: 6.2+ KB


In [46]:
#handling salary column to numeric datatypr instead of object
ds["Salary"]=pd.to_numeric(ds["Salary"],errors = 'coerce')

In [45]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype         
---  ------      --------------  -----         
 0   Name        100 non-null    object        
 1   Age         100 non-null    float64       
 2   Gender      86 non-null     object        
 3   Email       100 non-null    object        
 4   Join_Date   24 non-null     datetime64[ns]
 5   Salary      60 non-null     float64       
 6   Department  84 non-null     object        
dtypes: datetime64[ns](1), float64(2), object(4)
memory usage: 6.2+ KB


In [49]:
ds["Department"].unique()

array(['Admin', 'Engineering', 'HR', 'Sales', '-', 'Marketing'],
      dtype=object)

In [53]:
#finding mode for filling at nan place
x=ds["Department"].mode()
ds["Department"].fillna(x,inplace=True)

In [56]:
ds["Department"].unique()

array(['Admin', 'Engineering', 'HR', 'Sales', '-', 'Marketing'],
      dtype=object)

In [57]:
print(ds.to_string())

       Name   Age  Gender               Email  Join_Date   Salary   Department
0     Alice  35.0     NaN   user0@example.com 2021-05-21      NaN        Admin
1       Bob  40.0    Male   user1@example.com        NaT  50000.0  Engineering
2   Charlie  35.0    Male   user2@example.com        NaT  50000.0           HR
3     David  35.0     NaN   user3@example.com 2021-05-21  70000.0        Admin
4       Eva  35.0   Other   user4@example.com        NaT  70000.0  Engineering
5     Frank  35.0   Other   user5@example.com        NaT  70000.0        Admin
6     Grace  35.0  Female   user6@example.com        NaT  80000.0  Engineering
7    Hannah  35.0   Other   user7@example.com 2021-05-21      NaN           HR
8       Ivy  30.0  Female   user8@example.com        NaT  50000.0  Engineering
9      Jack  35.0    Male   user9@example.com        NaT  80000.0  Engineering
10    Alice  35.0    Male  user10@example.com 2021-05-21  70000.0  Engineering
11      Bob  35.0    Male  user11@example.com       

In [59]:
#to save data file
ds.to_csv("CleanedData.csv")